spring:
  application:
    name: BMS-from-jiax
  datasource:
    #    username: t1
    username: root
    password: 12345678
    #    url: jdbc:mysql://101.201.65.236:3306/ebick?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    url: jdbc:mysql://localhost:3306/ebick?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    cache: false
  messages:
    basename: i18n.login
mvc:
  static-path-pattern: /static/**

mqtt:
  brokerUrl: tcp://localhost:1883
  clientID: emqx-bms3
  username: admin
  password: public
server:
  port: 8080
  servlet:
    context-path: /web
mybatis:
  mapper-locations: classpath:mybatis/mapper/*/*.xml
  type-aliases-package: com.bms.pojo
  thymeleaf:
    prefix: classpath:/public/thymeleaf/